nevermined-io/sdk-dtp

- package.json
- src/AccessProofCondition.ts
- src/AccessProofTemplate.ts
- src/Dtp.ts
- src/NFT721AccessProofTemplate.ts
- src/NFT721SalesWithAccessTemplate.ts
- src/NFTAccessProofTemplate.ts
- src/NFTSalesWithAccessTemplate.ts
- src/ProofTemplate.ts
- src/utils.ts
- test/ConsumeAssetProof.test.ts
- test/ConsumeNFTAssetProof.test.ts
- test/NFTAccessProofTemplate.test.ts
- test/NFTTransferProofTemplate.test.ts
- test/RegisterAccessProofTemplate.test.ts
- test/utils.ts
> Service refactor

- .github/workflows/testing.yml
- package.json
- src/AccessProofTemplate.ts
- src/Dtp.ts
- src/Service.ts
> fix to the AccessProofTemplate

- package.json
Update to latest version of the sdk
> Update to latest sdk version

- package.json
- test/config.ts
> Using sdk 0.25.0-rc3 & removing Secret Store config

- test.data
- test/utils.test.ts
> additional test

- .github/workflows/release-npm.yml
- .github/workflows/testing-new-gateway.yml
- .github/workflows/testing.yml
- package.json
> Updating to sdk-js `v0.26.0`

- .github/workflows/testing-new-gateway.yml
- package.json
> last version of sdk

- .github/workflows/testing-new-gateway.yml
- package.json
- src/Dtp.ts
> Handling the return types of assets

- package.json
Update sdk-js to v1.0.0-rc5 version
> Update sdk-js to v1.0.0-rc5 version

- package.json
- src/AccessProofCondition.ts
- src/AccessProofTemplate.serviceAgreementTemplate.ts
- src/AccessProofTemplate.ts
- src/Dtp.ts
- src/KeyTransfer.ts
- src/NFT721AccessProofTemplate.serviceAgreementTemplate.ts
- src/NFT721AccessProofTemplate.ts
- src/NFT721SalesWithAccessTemplate.serviceAgreementTemplate.ts
- src/NFT721SalesWithAccessTemplate.ts
- src/NFTAccessProofTemplate.serviceAgreementTemplate.ts
- src/NFTAccessProofTemplate.ts
- src/NFTSalesWithAccessTemplate.serviceAgreementTemplate.ts
- src/NFTSalesWithAccessTemplate.ts
- src/ProofTemplate.ts
- src/Service.ts
- test/ConsumeAssetProof.test.ts
- test/ConsumeNFTAssetProof.test.ts
- test/NFTAccessProofTemplate.test.ts
- test/NFTTransferProofTemplate.test.ts
- test/RegisterAccessProofTemplate.test.ts
- test/config.ts
> Update/sdk 1.0.0 rc6

- .github/workflows/testing-new-gateway.yml
- package.json
- src/Dtp.ts
- src/NFTSalesWithAccessTemplate.ts
- test/GatewayTransfer.test.ts
- test/NFTTransferProofTemplate.test.ts
The sales with access flow should now work. Also using the normal flow for DTP assets for NFT sales.
> Ordering and accessing

- package.json
- src/AccessProofTemplate.ts
Remove interface duplicated in `sdk-js`
> remove interface duplicated in sdk

- .github/workflows/testing-new-gateway.yml
- .github/workflows/testing.yml
- package.json
- test/ConsumeNFTAssetProof.test.ts
Update sdk-js dependency to version 1.0.0-rc10.
> update sdk-js dependency to version 1.0.0-rc10

- package.json
> update to sdk 1.0.0 rc12

- package.json
> using sdk v1.0.0-rc15

- package.json
> bump sdk to rc20

- .github/workflows/testing-nightly.yml
- README.md
- package.json
- src/AccessProofCondition.ts
- src/AccessProofTemplate.serviceAgreementTemplate.ts
- src/AccessProofTemplate.ts
- src/Dtp.ts
- src/KeyTransfer.ts
- src/NFT721AccessProofTemplate.serviceAgreementTemplate.ts
- src/NFT721AccessProofTemplate.ts
- src/NFT721SalesWithAccessTemplate.serviceAgreementTemplate.ts
- src/NFT721SalesWithAccessTemplate.ts
- src/NFTAccessProofTemplate.serviceAgreementTemplate.ts
- src/NFTAccessProofTemplate.ts
- src/NFTSalesWithAccessTemplate.serviceAgreementTemplate.ts
- src/NFTSalesWithAccessTemplate.ts
- src/ProofTemplate.ts
- src/Service.ts
- test/ConsumeAssetProof.test.ts
- test/ConsumeNFTAssetProof.test.ts
- test/GatewayTransfer.test.ts
- test/NFTAccessProofTemplate.test.ts
- test/NFTTransferProofTemplate.test.ts
- test/RegisterAccessProofTemplate.test.ts
- test/config.ts
- test/utils.ts
- using new `@nevermined-io/sdk` dependency name
- renaming sdk dtp package to `@nevermined-io/sdk-dtp`
> Renaming NPM package names

- package.json
- use latest sdk
- bump version to v0.4.0
> feat: update to latest version of the sdk

- package.json
- update to sdk v1.2.0
- bump version to 0.4.1
> feat: update to latest sdk

- .github/workflows/testing-nightly.yml
- .github/workflows/testing.yml
- package.json
- test/config.ts
> update sdk version 1.3.0

- .github/workflows/testing-nightly.yml
- .github/workflows/testing.yml
- package.json
> sdk@1.3.2 version bump

- .github/workflows/testing.yml
- package.json
> feat: update to sdk version 1.3.6

- package.json
> SDK v1.3.9

- package.json
> update sdk to 1.3.10

- .github/workflows/testing-node.yml
- .github/workflows/testing.yml
- package.json
- test/ConsumeAssetDLEQ.test.ts
> feat: update to sdk version 1.3.13

- package.json
> Using SDK v1.3.14

- package.json
> Using SDK v.1.13.16

- package.json
> update sdk version to 1.4.1

- package.json
> chore: sdk v1.4.4

- .github/workflows/testing-nightly.yml
- .github/workflows/testing-node.yml
- .github/workflows/testing.yml
- package.json
> feat: bump version

- package.json
> feat: update sdk to 1.5.3

- package.json
> update to sdk 1.5.4

- .github/workflows/testing-node.yml
- .github/workflows/testing.yml
- README.md
- package.json
- src/Dtp.ts
- make the sdk a peer dependency
- update version of typescript
- update to support sdk 1.6.0
- bump version to 0.6.0
Closes https://github.com/nevermined-io/sdk-js/issues/554
> feat: make the sdk a peer dependency
